services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: simple-server
    networks:
      - my-custom-net


  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    container_name: simple-client
    depends_on:
      - server
    stdin_open: true
    tty: true
    networks:
      - my-custom-net

networks:
  my-custom-net:
    driver: bridge
